### ISSUE TITLE
Replace vendor tool vndr with dep.

### ISSUE THREAD

**Issue by dungeonmaster18** [alexellis/jaas#18]
**Description** 

I seen the to-do. It has migrating the repo to dep from vndr. So I have few questions.

- Should I add latest version or the version specified in the vendor.conf?
- As I couldn't find any other problems migrating to dep, so if anyone knows any can you just list it here.

Cc / @alexellis

**P.S** I would like work on this. So please suggest anything if I  have missed it.

**Comment by alexellis** [comment]
Be warned, this is not an easy task due to the way Moby and Docker split.

The path of least resistance is going to be to copy what we did on faas-swarm where we pinned specific versions of both components. A regular `dep init` is unlikely to work

https://github.com/openfaas/faas-swarm/blob/master/Gopkg.toml#L8

If you do work on this and get it fully working then please exclude the resultig huge vendor folder from the PR. :+1:
